### ISSUE TITLE
Error data: yarn failed

### ISSUE THREAD

**Issue by deivismac** [jonassvensson4/jsfour-core#1]
does this mean i have to install the dependencies myself ?? i tried reinstalling, and restarting server multiple times

**Comment by jnsvns** [comment]
Please read the instructions found in the READme:

It's recommended to run the resource once and then restart the server since it's generating some modules.

If yarn decides to stop working try this:
- Reinstall yarn
- Restart your server and rerun in
- If it won't download all the modules you could install the modules by using npm. You'll find the modules to install in the package.json under dependencies.
